/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.event.*;
import java.util.*;
import java.sql.*;
import java.text.DecimalFormat;
/**
 *
 * @author zz
 */
public class kassa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kassa.class.getName());

    /**
     * Creates new form kassa
     */
    public kassa() {
        initComponents();
    
    DefaultListModel<String> modelRight = new DefaultListModel<>();
    DefaultListModel<String> modelLeft  = new DefaultListModel<>();

 jList1.setModel(modelRight);
    jList2.setModel(modelLeft);

 //загрузка из базы
    loadMenuFromDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Занести");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Убрать");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Заказать");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel1.setText("заказано");

        jLabel2.setText("Позиции");

        jButton4.setText("Отчет");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if (jList1.isSelectionEmpty()) {
        JOptionPane.showMessageDialog(this, "Выберите позицию из меню");
        return;
    }
    
    String выбраннаяПозиция = jList1.getSelectedValue();
    
   //перенос влево
    DefaultListModel<String> modelLeft = (DefaultListModel<String>) jList2.getModel();
    modelLeft.addElement(выбраннаяПозиция);
    
   
    jList2.ensureIndexIsVisible(modelLeft.getSize() - 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       DefaultListModel<String> model = (DefaultListModel<String>) jList2.getModel();
    
    if (model.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Чек пустой!", "Внимание", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Connection conn = null;
    PreparedStatement psOrder = null;
    PreparedStatement psItem = null;
    ResultSet rs = null;

    try {
        conn = DbConnection.getConnection();
        conn.setAutoCommit(false);  

        // 1. Считаем сумму и количество позиций
        double totalSum = 0.0;
        int itemCount = model.getSize();

        for (int i = 0; i < itemCount; i++) {
            String line = model.get(i);
            String[] parts = line.split(" — ");
            if (parts.length != 2) continue;

            String priceStr = parts[1].replace(" ₽", "").replace(",", ".").trim();
            double price = Double.parseDouble(priceStr);
            totalSum += price;
        }

        // 2. Создаём запись в orders_report
        String sqlOrder = "INSERT INTO orders_report (total_sum, items_count, status) VALUES (?, ?, 'в обработке') RETURNING order_id";
        psOrder = conn.prepareStatement(sqlOrder);
        psOrder.setDouble(1, totalSum);
        psOrder.setInt(2, itemCount);
        rs = psOrder.executeQuery();

        int orderId = 0;
        if (rs.next()) {
            orderId = rs.getInt("order_id");
        }

        // 3. Записываем позиции в order_items
        String sqlItem = "INSERT INTO order_items (order_id, item_name, price, quantity) VALUES (?, ?, ?, 1)";
        psItem = conn.prepareStatement(sqlItem);

        for (int i = 0; i < itemCount; i++) {
            String line = model.get(i);
            String[] parts = line.split(" — ");
            if (parts.length != 2) continue;

            String itemName = parts[0].trim();
            String priceStr = parts[1].replace(" ₽", "").replace(",", ".").trim();
            double price = Double.parseDouble(priceStr);

            psItem.setInt(1, orderId);
            psItem.setString(2, itemName);
            psItem.setDouble(3, price);
            psItem.addBatch();
        }

        psItem.executeBatch();

        // 4. Фиксируем изменения
        conn.commit();

        
        JOptionPane.showMessageDialog(this,
            "Чек №" + orderId + " успешно сохранён в отчёте!\n" +
            "Сумма: " + String.format("%,.2f ₽", totalSum) + "\n" +
            "Статус: в обработке",
            "Успех",
            JOptionPane.INFORMATION_MESSAGE);

        // Очищаем текущий заказ
        model.clear();

    } catch (Exception ex) {
        
        try { if (conn != null) conn.rollback(); } catch (Exception ignored) {}
        
        JOptionPane.showMessageDialog(this,
            "Ошибка при сохранении чека:\n" + ex.getMessage(),
            "Ошибка",
            JOptionPane.ERROR_MESSAGE);
        
        ex.printStackTrace();

    } finally {
       
        try { if (rs != null) rs.close(); } catch (Exception ignored) {}
        try { if (psItem != null) psItem.close(); } catch (Exception ignored) {}
        try { if (psOrder != null) psOrder.close(); } catch (Exception ignored) {}
        try { if (conn != null) conn.close(); } catch (Exception ignored) {}
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> model = (DefaultListModel<String>) jList2.getModel();
    
    
    int[] selectedIndices = jList2.getSelectedIndices();
    
    if (selectedIndices.length == 0) {
        return; 
    }
    
    
    for (int i = selectedIndices.length - 1; i >= 0; i--) {
        model.remove(selectedIndices[i]);
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Otchet otchetForm = new Otchet();
    otchetForm.setVisible(true);
    

    
    // отчёт открывался поверх кассы
    otchetForm.setAlwaysOnTop(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kassa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

   private void loadMenuFromDatabase() {
    DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();
        model.clear();

        try (Connection conn = DbConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT name, price FROM menu_items ORDER BY name");
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                String name = rs.getString("name");
                double price = rs.getDouble("price");
                model.addElement(name + " — " + String.format("%.2f ₽", price));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Не удалось загрузить меню из базы.\n" + ex.getMessage(),
                "Ошибка",
                JOptionPane.ERROR_MESSAGE);
        }
    }

   
}