/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingConstants;
import java.awt.Font;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author zz
 */
public class Otchet extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Otchet.class.getName());

    /**
     * Creates new form Otchet
     */
    public Otchet() {
        initComponents();


   
   jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    // Заполняем комбобокс ОДИН РАЗ при создании формы
    jComboBox1.removeAllItems();
    jComboBox1.addItem("За неделю");
    jComboBox1.addItem("За месяц");
    jComboBox1.addItem("За год");
    jComboBox1.setSelectedIndex(0); // по умолчанию неделя

    jButton2.addActionListener(evt -> changeOrderStatus("выполнен"));
    jButton3.addActionListener(evt -> changeOrderStatus("отменён"));
 
    };
    
    
            
        private void changeOrderStatus(String newStatus) {
    int selectedRow = jTable2.getSelectedRow();
    if (selectedRow < 0) {
        return;  
    }

    Object idValue = jTable2.getValueAt(selectedRow, 0);
    if (!(idValue instanceof Integer)) {
        return;  
    }

    int orderId = (Integer) idValue;

    String sql = "UPDATE orders_report SET status = ? WHERE order_id = ?";

    try (Connection conn = DbConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, newStatus);
        ps.setInt(2, orderId);

        int rows = ps.executeUpdate();

        if (rows > 0) {
            
            jButton1.doClick();
        }
       

    } catch (SQLException ex) {
        // ошибки показываем только в консоль (или вообще убрать)
        System.err.println("Ошибка изменения статуса заказа #" + orderId + ": " + ex.getMessage());
        ex.printStackTrace();
    }
}  
            /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("отчет");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Подтвердить");

        jButton3.setText("Отменить");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(49, 49, 49)
                .addComponent(jButton3)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.removeAllItems();
jComboBox1.addItem("За неделю");
jComboBox1.addItem("За месяц");
jComboBox1.addItem("За год");
jComboBox1.setSelectedIndex(0); 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                               
                                          
    String period = (String) jComboBox1.getSelectedItem();
    if (period == null) {
        JOptionPane.showMessageDialog(this, "Выберите период");
        return;
    }

    String interval;
    switch (period) {
        case "За неделю":  interval = "7 days";   break;
        case "За месяц":   interval = "1 month";  break;
        case "За год":     interval = "1 year";   break;
        default:           interval = null;       break;
    }

    String whereClause = (interval != null) 
        ? "order_date >= CURRENT_DATE - INTERVAL '" + interval + "'" 
        : "TRUE";  // все записи

    String sql = """
        SELECT 
            order_id,
            order_date,
            total_sum,
            status
        FROM orders_report
        WHERE %s
        ORDER BY order_date DESC
        """.formatted(whereClause);

    DefaultTableModel model = new DefaultTableModel(
        new String[]{"Заказ #", "Дата и время", "Сумма ₽", "Статус"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    double grandTotal = 0.0;
    int orderCount = 0;

    try (Connection conn = DbConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("order_id");
            java.sql.Timestamp ts = rs.getTimestamp("order_date");
            double sum = rs.getDouble("total_sum");
            String st = rs.getString("status");

            // Красивая дата-время
            String dateTime = (ts != null) 
                ? ts.toLocalDateTime().toString().substring(0, 19).replace("T", " ") 
                : "—";

            model.addRow(new Object[]{
                id,
                dateTime,
                String.format("%,.2f", sum),
                st != null ? st : "—"
            });

            grandTotal += sum;
            orderCount++;
        }

        // Итог
        if (orderCount > 0) {
            model.addRow(new Object[]{
                "ИТОГО",
                orderCount + " заказов",
                String.format("%,.2f ₽", grandTotal),
                ""
            });
        } else {
            model.addRow(new Object[]{"Нет заказов за период", "", "", ""});
        }

        jTable2.setModel(model);

        // Выравнивание суммы
        DefaultTableCellRenderer right = new DefaultTableCellRenderer();
        right.setHorizontalAlignment(SwingConstants.RIGHT);
        jTable2.getColumnModel().getColumn(2).setCellRenderer(right);

        // Твой рендерер цветов (оставил как есть, он уже хороший)
        jTable2.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                c.setForeground(java.awt.Color.BLACK);
                c.setFont(c.getFont().deriveFont(java.awt.Font.PLAIN));

                String firstCell = table.getValueAt(row, 0).toString();
                if ("ИТОГО".equals(firstCell)) {
                    c.setForeground(java.awt.Color.BLACK);
                    c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD));
                    return c;
                }

                if (column == 3 && value != null) {
                    String status = value.toString().trim().toLowerCase();
                    if (status.contains("обработ")) {
                        c.setForeground(new java.awt.Color(0, 100, 255));
                    } else if (status.contains("выполнен")) {
                        c.setForeground(new java.awt.Color(0, 140, 0));
                    } else if (status.contains("отмен")) {
                        c.setForeground(new java.awt.Color(220, 0, 0));
                    } else {
                        c.setForeground(java.awt.Color.DARK_GRAY);
                    }
                    c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD));
                }

                if (isSelected) {
                    c.setBackground(table.getSelectionBackground());
                    c.setForeground(table.getSelectionForeground());
                }

                return c;
            }
        });

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Ошибка:\n" + ex.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }


    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Otchet().setVisible(true));
    }
private void loadOrderDetails(int orderId, JTable table, JLabel summaryLabel) {
    DefaultTableModel model = new DefaultTableModel(
        new String[]{"Товар", "Цена", "Кол-во", "Сумма"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int col) { return false; }
    };

    double total = 0.0;
    String status = "—";

    try (Connection conn = DbConnection.getConnection()) {
        // 1. Общая информация о заказе
        PreparedStatement psOrder = conn.prepareStatement(
            "SELECT total_sum, status FROM orders_report WHERE order_id = ?");
        psOrder.setInt(1, orderId);
        ResultSet rsOrder = psOrder.executeQuery();
        
        if (rsOrder.next()) {
            total = rsOrder.getDouble("total_sum");
            status = rsOrder.getString("status");
        }

        // 2. Позиции заказа
        PreparedStatement psItems = conn.prepareStatement(
            "SELECT item_name, price, quantity FROM order_items WHERE order_id = ?");
        psItems.setInt(1, orderId);
        ResultSet rsItems = psItems.executeQuery();

        while (rsItems.next()) {
            String name = rsItems.getString("item_name");
            double price = rsItems.getDouble("price");
            int qty = rsItems.getInt("quantity");
            double sum = price * qty;

            model.addRow(new Object[]{
                name,
                String.format("%,.2f ₽", price),
                qty,
                String.format("%,.2f ₽", sum)
            });
        }

        // 3. Итог
        summaryLabel.setText(String.format("Итого: %,.2f ₽   Статус: %s", total, status));

        table.setModel(model);

        // выравнивание цен по правому краю
        table.getColumnModel().getColumn(1).setCellRenderer(new DefaultTableCellRenderer() {
            { setHorizontalAlignment(SwingConstants.RIGHT); }
        });
        table.getColumnModel().getColumn(3).setCellRenderer(new DefaultTableCellRenderer() {
            { setHorizontalAlignment(SwingConstants.RIGHT); }
        });

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,
            "Не удалось загрузить детали чека:\n" + ex.getMessage(),
            "Ошибка", JOptionPane.ERROR_MESSAGE);
    }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}